#!/usr/bin/python2.7

import logging, sys
logging.getLogger("scapy.runtime").setLevel(logging.ERROR)
from rc4 import rc4
from lib.crypto import Wep, Wpa
from scapy.all import *

wepCrypto = Wep()
wpaCrypto = Wpa()
keyText = '0123456789'
wepICMP = rdpcap('PCAPs/wep_pings.pcap')
openICMP = rdpcap('PCAPs/open_pings.pcap')



### WEP PORTION
def wepDecrypt(pkt, keyText = keyText, method = 'pcap'):
    """Encompasses the steps needed to decrypt a WEP packet"""
    if method == 'pcap':
        pkt = pkt.copy()
    fullStream, stream, iVal, seed = wepCrypto.decoder(pkt, keyText)
    decodedPacket = wepCrypto.deBuilder(pkt, fullStream)

    ## Flip FCField bits accordingly
    if decodedPacket[Dot11].FCfield == 65L:
        decodedPacket[Dot11].FCfield = 1L
    elif decodedPacket[Dot11].FCfield == 66L:
        decodedPacket[Dot11].FCfield = 2L
    
    return decodedPacket, iVal


def wepEncrypt(pkt, iVal = '\xba0\x0e', keyText = keyText, method = 'pcap'):
    """Encompasses the steps needed to encrypt a WEP packet"""
    if method == 'pcap':
        pkt = pkt.copy()
       
    ## Encode the LLC layer via rc4
    stream, wepICV = wepCrypto.encoder(pkt, iVal, keyText)

    ## This is our newly minted packet!
    encodedPacket = wepCrypto.enBuilder(pkt, stream, iVal, wepICV)    

    ## Flip FCField bits accordingly
    if encodedPacket[Dot11].FCfield == 1L:
        encodedPacket[Dot11].FCfield = 65L
    elif encodedPacket[Dot11].FCfield == 2L:
        encodedPacket[Dot11].FCfield = 66L

    return encodedPacket



### WPA PORTION
def eapolGrab():
    """Grab the EAPOL
    Needs logic in case of multiple auth at one
    """
    pkts = sniff(iface = 'wlan0mon', lfilter = lambda p: p.haslayer(EAPOL) and p.type == 2, count = 4)
    vMAC = pkts[0][Dot11].addr1
    bMAC = pkts[0][Dot11].addr2
    eapolCapture = wpaCrypto.shakeDict[vMAC] = {}
    eapolCapture[bMAC] = pkts
    return vMAC, bMAC

def wpaHandshake():
    """Store EAPOLs based upon BSSID based upon originating MAC"""
    vMAC, bMAC = eapolGrab()
    vicMAC = wpaCrypto.shakeDict[vMAC]
    bDict = vicMAC[bMAC]


### Lazy help menu
try:
    if sys.argv[1] == '--help':
        print 'Perform the following for WEP:'
        print '  ipython'
        print '  %run pyDot11' 
        print '  pkt = wepDecrypt(wepICMP[0])'
        print '  pkt'
        print '  ## Want to play with your own packets?'
        print '  pkt = wepDecrypt(packet, keyText = <password for the WEP>)\n'
        print 'Perform the following for WPA:'
        print '  wpaHandshake():'
except:
    pass
