#!/usr/bin/python2.7

import logging, sys
logging.getLogger("scapy.runtime").setLevel(logging.ERROR)
try:
    from scapy.all import *
except:
    print 'scapy from pip must be installed to continue\n'
    exit(1)
from lib.crypto import Wep

wepCrypto = Wep()
keyText = '0123456789'
wepICMP = rdpcap('../PCAPs/ICMPs/wep_pings.pcap')
openICMP = rdpcap('../PCAPs/ICMPs/open_pings.pcap')

### Example of decoding
## This is our packet grabbed via scapy on wlan0mon
ePkt = wepICMP[3].copy()

## This is a decoded wepdata string
stream, iVal, seed = wepCrypto.decoder(ePkt, keyText)

## This is our newly minted packet
decodedPacket = wepCrypto.deBuilder(ePkt, stream)


### Example of Encoding
## Encode the LLC layer via rc4
stream, wepICV = wepCrypto.encoder(decodedPacket, iVal, keyText)

## This is our newly minted packet
outPacket = wepCrypto.enBuilder(decodedPacket, stream, iVal, wepICV)

## Display results
print 'Original:'
print ePkt[Dot11WEP].show()
print ''
print 'New:'
print outPacket[Dot11WEP].show()
print ''
print 'wepdata compare:'
print ePkt[Dot11WEP].wepdata == outPacket[Dot11WEP].wepdata
print ''
print 'icv compare:'
print ePkt[Dot11WEP].icv == outPacket[Dot11WEP].icv
